##
## EPITECH PROJECT, 2023
## Makefile_src
## File description:
## Makefile_src
##


NAME	=	my_rpg

SRC	+= src/main.c

SRC	+= src/debug/check_malloc.c

SRC += src/collisions/mouse/mouse_over_circle.c
SRC += src/collisions/mouse/mouse_over_rect.c

SRC += src/game/init/init_game.c
SRC += src/game/init/init_game_data.c
SRC += src/game/update/update_game.c
SRC += src/game/events/events_game.c

SRC += src/fight/init/init_fight.c
SRC += src/fight/init/set_fight_menu.c
SRC += src/fight/init/set_characters.c
SRC += src/fight/init/new_fight_text.c
SRC += src/fight/events/events_fight.c
SRC += src/fight/events/events_fight_menu.c
SRC += src/fight/events/events_attack.c
SRC += src/fight/events/move_charac.c
SRC += src/fight/events/animate_attack.c
SRC += src/fight/events/update_attack_cooldown.c
SRC += src/fight/events/update_hp.c
SRC += src/fight/events/animate_die.c
SRC += src/fight/events/end_fight.c
SRC += src/fight/update/update_fight.c
SRC += src/game/events/move_player.c
SRC += src/game/load/load.c

SRC += src/menu/main/init/init_main_menu.c
SRC += src/menu/main/update/update_main_menu.c
SRC += src/menu/main/events/events_main_menu.c
SRC += src/menu/settings/init/init_settings_menu.c
SRC += src/menu/settings/update/update_settings_menu.c
SRC += src/menu/settings/events/events_settings_menu.c
SRC += src/menu/settings/events/game_changes.c
SRC += src/menu/settings/events/sound_events.c
SRC += src/menu/menu_run.c
SRC += src/menu/ig_menu/init/init_ig_menu.c
SRC += src/menu/ig_menu/update/update_ig_menu.c
SRC += src/menu/ig_menu/events/events_ig_menu.c

SRC += src/parser/init_parser.c
SRC += src/parser/get_info_nb.c
SRC += src/parser/str_to_array_separator.c

SRC += src/destroy/destroy_game.c
SRC += src/destroy/destroy_menu.c
SRC += src/destroy/destroy_settings.c
SRC += src/destroy/button_destroy.c
SRC += src/destroy/map_editor_destroy.c

SRC += src/tile/tile_create.c
SRC += src/tile/tile_destroy.c
SRC += src/tile/grid/grid_create.c
SRC += src/tile/grid/grid_destroy.c
SRC += src/tile/grid/grid_draw.c
SRC += src/tile/tile_set.c

SRC += src/map_editor/event/delete_event.c
SRC += src/map_editor/event/edit_obj/edit_obj_add.c
SRC += src/map_editor/event/edit_obj/edit_obj_create.c
SRC += src/map_editor/event/edit_obj/edit_obj_destroy.c
SRC += src/map_editor/event/edit_obj/edit_obj_get.c
SRC += src/map_editor/event/edit_obj/edit_obj_remove.c
SRC += src/map_editor/event/edit_obj/edit_obj_draw.c
SRC += src/map_editor/event/edit_obj/edit_obj_clear.c
SRC += src/map_editor/event/window_popUP/create_pop_up.c
SRC += src/map_editor/event/window_popUP/update_pop_up.c
SRC += src/map_editor/event/window_popUP/events_pop_up.c
SRC += src/map_editor/event/window_popUP/text_events.c
SRC += src/map_editor/event/map_editor_event.c
SRC += src/map_editor/event/map_editor_update_grid.c
SRC += src/map_editor/event/open_file_map_event.c
SRC += src/map_editor/event/save_grid_event.c
SRC += src/map_editor/event/map_editor_col_event.c
SRC += src/map_editor/event/update_tools_selection.c
SRC += src/map_editor/event/swap_set_event.c
SRC += src/map_editor/event/update_tile_place.c
SRC += src/map_editor/event/hide_set.c
SRC += src/map_editor/event/update_selected.c
SRC += src/map_editor/event/map_editor_exit.c
SRC += src/map_editor/event/new_grid_event.c
SRC += src/map_editor/event/handle_view_event.c
SRC += src/map_editor/event/map_edit_unit_event.c
SRC += src/map_editor/init/button/button_create.c
SRC += src/map_editor/init/button/button_draw.c
SRC += src/map_editor/init/button/map_editor_init_buttons.c
SRC += src/map_editor/init/file_map/file_get_map_data.c
SRC += src/map_editor/init/file_map/file_to_map.c
SRC += src/map_editor/init/file_map/update_idx_arg.c
SRC += src/map_editor/init/file_map/file_to_map_unit.c
SRC += src/map_editor/init/map_editor_init.c
SRC += src/map_editor/init/tile/map_editor_tile_add_colision.c
SRC += src/map_editor/init/tile/tile_pos_set_init.c
SRC += src/map_editor/init/tile/tile_pos_set_add.c
SRC += src/map_editor/init/tile/tile_pos_set_update.c
SRC += src/map_editor/init/tile_coord_set/tile_coord_set_add.c
SRC += src/map_editor/init/tile_coord_set/tile_coord_set_create.c
SRC += src/map_editor/init/tile_coord_set/tile_coord_set_remove.c
SRC += src/map_editor/init/tile_coord_set/tile_coord_set_destroy.c
SRC += src/map_editor/init/tile_coord_set/grid_tile_coord_set_init.c
SRC += src/map_editor/init/list_text_init.c
SRC += src/map_editor/map_editor.c
SRC += src/map_editor/save_grid.c
SRC += src/map_editor/update/map_editor_draw.c
SRC += src/map_editor/update/map_editor_handle_screen.c
SRC += src/map_editor/update/update_colision.c
SRC += src/map_editor/update/update_map_edit_open.c
SRC += src/map_editor/text_list/text_list_add.c
SRC += src/map_editor/text_list/text_list_create.c
SRC += src/map_editor/text_list/text_list_destroy.c
SRC += src/map_editor/text_list/text_list_display.c
SRC += src/map_editor/text_list/text_list_remove.c
SRC += src/map_editor/text_list/text_list_change.c
SRC += src/map_editor/text_list/text_list_find.c
SRC += src/map_editor/text_list/text_list_update.c
SRC += src/map_editor/text_list/text_set_pos.c
SRC += src/map_editor/game_unit/game_unit_list_add.c
SRC += src/map_editor/game_unit/game_unit_list_create.c
SRC += src/map_editor/game_unit/game_unit_list_destroy.c
SRC += src/map_editor/game_unit/game_unit_list_draw.c
SRC += src/map_editor/game_unit/game_unit_list_remove.c
SRC += src/map_editor/init/map_editor_init_set.c

SRC += src/test_area/test_area_run.c
SRC += src/test_area/test_area_draw.c
SRC += src/test_area/test_area_update.c
SRC += src/test_area/test_area_event.c
SRC += src/test_area/interact/sword_interact.c
SRC += src/test_area/interact/exit_interact.c
SRC += src/test_area/test_area_init.c
SRC += src/test_area/gm_reset_data.c
SRC += src/test_area/test_room/test_room_init.c
SRC += src/test_area/test_room/test_room_run.c
SRC += src/test_area/gm_destroy_data.c

SRC += src/player/player_set_pos.c
SRC += src/player/player_update.c
SRC += src/player/player_can_move.c

SRC += src/game_actor/game_actor_add.c
SRC += src/game_actor/game_actor_list_create.c
SRC += src/game_actor/game_actor_list_destroy.c
SRC += src/game_actor/game_actor_remove.c
SRC += src/game_actor/game_actor_list_draw.c
SRC += src/game_actor/colision/game_actor_colision_line.c
SRC += src/game_actor/colision/game_actor_collision_square.c
SRC += src/game_actor/colision/game_actor_is_in_range.c
SRC += src/game_actor/event/game_actor_list_event.c
SRC += src/game_actor/game_actor_list_clear.c
SRC += src/game_actor/animation/game_actor_list_anim.c

SRC += src/map/init/room_init.c
SRC += src/map/init/room2_init.c
SRC += src/map/init/midlayer_init.c
SRC += src/map/init/undergr_init.c
SRC += src/map/init/outside_init.c
SRC += src/map/init/nihil_init.c

SRC += src/map/event/room_event.c
SRC += src/map/event/room2_event.c
SRC += src/map/event/midlayer_event.c
SRC += src/map/event/undergr_event.c
SRC += src/map/event/outside_event.c
SRC += src/map/event/nihil_event.c

SRC += src/map/interact/room/room_interact_book.c
SRC += src/map/interact/room/room_interact_go_room2.c
SRC += src/map/interact/room/room_interact_go_midlayer.c

SRC += src/map/interact/room2/room2_interact_go_room.c
SRC += src/map/interact/room2/room2_interact_book.c
SRC += src/map/interact/room2/room2_interact_chest.c

SRC += src/map/interact/midlayer/midlayer_interact_go_undergr.c
SRC += src/map/interact/midlayer/midlayer_interact_go_room.c
SRC += src/map/interact/midlayer/midlayer_interact_go_outside.c

SRC += src/map/interact/undergr/undergr_interact_go_midlayer.c

SRC += src/map/interact/outside/outside_interact_go_midlayer.c
SRC += src/map/interact/outside/outside_interact_npc.c
SRC += src/map/interact/outside/outside_interact_go_nihil.c

SRC += src/map/interact/nihil/nihil_interact_book.c
SRC += src/map/interact/nihil/nihil_interact_npc.c

SRC += src/map/map_init.c
SRC += src/map/map_run.c
SRC += src/map/map_event.c
SRC += src/map/map_update.c
SRC += src/map/map_draw.c

SRC += src/destroy/destroy_fight.c


SRC += src/player/stats/event/events_skill_tree.c
SRC += src/player/stats/init/init_skill_tree.c
SRC += src/player/stats/init/init_stat_hud.c
SRC += src/player/stats/update/update_skill_tree.c
SRC += src/player/stats/update/update_stat_hud.c

SRC += src/npc/events/events_npc.c
SRC += src/npc/events/npc_move.c
SRC += src/npc/events/npc_exclamation.c
SRC += src/npc/init/init_npc.c
SRC += src/npc/update/update_npc.c
SRC += src/npc/events/npc_move_ver1.c

SRC += src/scene/scene_change.c
SRC += src/scene/handle_save.c
SRC += src/scene/handle_save_pos.c

SRC += save/handle_save/reset_current_save.c

SRC += src/menu/how_to_play/update/update_how_to_play_scene.c

SRC += src/inventory/events/events_inventory.c
SRC += src/inventory/init/init_inventory.c
SRC += src/inventory/update/update_inventory.c

SRC += src/description/handle_help.c

LIBS = *.a

OBJ		=		$(SRC:.c=.o)

MSL		=		-I lib/msl/includes/msl

PSL		=		-I lib/msl/includes/psl

SSL		=		-I lib/msl/includes/ssl

CSL		=		-I lib/msl/includes/csl

MLIB	=		-I lib/msl/includes/


CSFML	=	-lcsfml-system -lcsfml-window -lcsfml-audio -lcsfml-graphics

CFLAGS	=		-I includes/ $(MLIB) $(CSL) $(MSL) $(PSL) $(SSL)

LIB		=		lib/libmsl.a

LIB += -L./lib/will/ -l:libw_printf.a -L./lib/will/ -l:libtools.a


all:	make_lib $(OBJ)
	@gcc -o $(NAME) $(OBJ) $(LIB) $(CSFML) -Wall -Wextra -g -lm -Wall -Wextra
	@echo "\e[1;32mCompilation done\e[0m"

make_lib:
	@ $(MAKE) -sC lib/msl/ --no-print-directory
	@ $(MAKE) -sC lib/will/tools/
	@ $(MAKE) -sC lib/will/w_printf/

%.o:	%.c
	@gcc $(CFLAGS) -c $< -o $@

clean:
	@ $(MAKE) fclean -sC lib/msl/ --no-print-directory
	@ $(MAKE) fclean -sC lib/will/tools/
	@ $(MAKE) fclean -sC lib/will/w_printf/
	@rm -rf lib/$(LIBS)
	@rm -rf $(OBJ)
	@rm -f src/$(OBJ)
	@rm -f coding-style-reports.log
	@echo "\e[1;31mclean done\e[0m"

coding-style:
	coding-style.sh . .
	cat coding-style-reports.log
	rm -rf coding-style-reports.log

fclean:	clean
	@rm -rf $(NAME)
	@echo "\e[1;31mfclean done\e[0m"

re:	fclean	all
